/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    Avatar: typeof import('./components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./components/ui/avatar/AvatarImage.vue')['default']
    Breadcrumb: typeof import('./components/ui/breadcrumb/Breadcrumb.vue')['default']
    BreadcrumbEllipsis: typeof import('./components/ui/breadcrumb/BreadcrumbEllipsis.vue')['default']
    BreadcrumbItem: typeof import('./components/ui/breadcrumb/BreadcrumbItem.vue')['default']
    BreadcrumbLink: typeof import('./components/ui/breadcrumb/BreadcrumbLink.vue')['default']
    BreadcrumbList: typeof import('./components/ui/breadcrumb/BreadcrumbList.vue')['default']
    BreadcrumbPage: typeof import('./components/ui/breadcrumb/BreadcrumbPage.vue')['default']
    BreadcrumbSeparator: typeof import('./components/ui/breadcrumb/BreadcrumbSeparator.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./components/ui/sheet/SheetTrigger.vue')['default']
    Sonner: typeof import('./components/ui/sonner/Sonner.vue')['default']
    Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
